### ISSUE TITLE
Is it possible add "show avatar from twitch" for chat bubbles?

### ISSUE THREAD

**Issue by Cloudstrifeff7** [zaytri/stream-elements-widgets#2]
Good morning, thank you very much for this chat which is really good. I now don't know how to apply for this addition so I try here.
I have seen the "show badges" option, so I ask if it is possible to add a similar option also to show the avatars of each user who writes in the chat. Thank you very much in advance!

**Comment by zaytri** [comment]
It is possible, however avatars have almost no regulation. You cannot guarantee that a random chatter will always have a stream appropriate avatar.

I have created an avatar feature for custom commissions before, but it would only show for VIPs and Moderators, because those are community members that the streamer has personally vetted. Even in those cases it's not 100% safe.

**Comment by zaytri** [comment]
If you would like to make your own fork with avatar support, feel free to.

You can get a user's avatar using DecAPI: https://docs.decapi.me/twitch?endpoint=avatar%2F%3Auser

However I am not planning on adding official support for it.

**Comment by Cloudstrifeff7** [comment]
I see. Thanks!
