### ISSUE TITLE
ChatBubbles User-Filter Follower not shown

### ISSUE THREAD

**Issue by MoeHunt3r** [zaytri/stream-elements-widgets#6]
Hey there, 
when in the User Filters Field  "Show messages from everyone" is set to "no" and "Show messages from Followers" is set to "yes" with a minimum of 1 Day, the Followers aren't showing up at all. Even when they're following more than 1 month.

**Comment by zaytri** [comment]
Seems that the DecAPI endpoint I was using to check follow date now requires additional authentication.

> Missing `token` parameter required for /twitch/followed as of September 2023 - A moderator or the broadcaster needs to authenticate to use followed

I could add a field for users to add that token so that the follow check works correctly, however the biggest issue is there's no way for me to add the authentication link in the settings due to SE limiting the character count in there.

I guess I could use a URL shortener?

**Comment by zaytri** [comment]
SE does have a `!followage` command available, so it does have access to it, however it doesn't expose that access in the data it feeds thru to custom widgets

**Comment by zaytri** [comment]
I'm not planning on adding the follower filter feature back into this, but I will have it when the Chat Bubbles are ported over to slime2

In the meantime, I added a new Message Filter to hide first-time chat messages https://github.com/zaytri/stream-elements-widgets/commit/ae634e2aa8063f273210fc8605649e583b9318e4
